# This workflow is to automate Checkmarx SCA scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_SCA_USERNAME
#   - CHECKMARX_SCA_PASSWORD
#
# The following variables must be inserted below:
#   - <ProjectName>
#   - <SCATenant>
#   - <GitHubRepoUrl>
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx SCA Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.8 # GitHub Action version
      with:
        project: jsb-sca-cxflow-test
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: ${{ secrets.CHECKMARX_SCA_TENANT }}
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }}
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }}
        team: ${{ secrets.CHECKMARX_SCA_TEAM }}
        break_build: true
        scanners: sca
        bug_tracker: Sarif
        params: >-
            --logging.level.com.checkmarx=DEBUG
            --namespace=${{ github.repository_owner }}
            --checkmarx.settings-override=true
            --repo-name=${{ github.event.repository.name }}
            --branch=${{ github.ref_name }}
            --repo-url="https://github.com/james-bostock-cx/cxflow-github-action-test"
            --sca.thresholds-severity.HIGH=10
    - name: Upload SARIF files
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./cx.sarif
      
